config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "todoos#index"
  resources :todoos, only: [:new, :create, :index] do 
    resource :completion, only: :create
  end
  resources :sessions, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/models/todoo.rb
class Todoo < ApplicationRecord
  def completed?
    completed_at?
  end
end

app/models/user.rb
class User

  def initialize(email)
    @email = email
  end

  def todoos
    Todoo.where(email: @email)
  end

  def signed_in?
    @email.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate
    redirect_to new_session_path unless user_signed_in?
  end

  def user_signed_in?
    current_user.signed_in?
  end

  def sign_in_as(email)
    session[:current_email] = email
  end

  def current_user
    User.new(session[:current_email])
  end
end

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
  def create
    current_user.todoos.find(params[:todoo_id]).touch :completed_at
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    sign_in_as params[:session][:email]
    redirect_to root_path
  end
end

app/controllers/todoos_controller.rb
class TodoosController < ApplicationController
  before_action :authenticate

  def index
    @todoos = current_user.todoos
  end

  def new
    @todoo = Todoo.new
  end

  def create
    @todoo = current_user.todoos.create(todoo_params)
    redirect_to todoos_path
  end

  private

  def todoo_params
    params.require(:todoo).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Todos</h1>
    <%= yield %>
  </body>
</html>

app/views/todoos/index.html.erb
<%= link_to "Add a new todo", new_todoo_path %>

<ul class="todo">
  <%= @todoos.each do |t| %>
    <li class="<%= "completed" if t.completed? %>">
    <%= t.title %>
    <%= link_to "Mark complete", todoo_completion_path(t.id), method: :post %>
    </li>
  <% end %>
</ul>

app/views/todoos/new.html.erb
<%= form_for @todoo do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit "Submit" %>
<% end %>